---
title: Colombian network of high energy physics
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ConHEP
email: comhep@gmail.com
baseurl: ""
admision: "/admision"
indicador: "/indicador"
contacto: "/contacto"
url: ""
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- vendor
- Procfile
- Rakefile
- TODO.md
include:
- _pages
categories:
- pregrado
- posgrado
- personal
- curso
- servicio
favicon: "/images/favicon.png"
twitter_username: PosgradosUdeA
fb_username: PosgradosUdeAntioquia
permalink: post/:year/:month/:day/:title
markdown: kramdown
authors:
  Posgrados Instituto de Física:
    display_name: Facultad de Ciencias Exactas y Naturales
    email: posgrados@gfif.udea.edu.co
    fb: PosgradosUdeAntioquia
    twitter: PosgradosUdeA
